// Precompiled theme bundles (generated by src/tools/build-theme-bundle.ts)
// are plain ESM modules; the Workers entry point imports them statically so
// no code evaluation happens at runtime.
declare module '*/bundle.mjs' {
    import type {ThemeBundle} from '../frontend/themes/types.js';
    const bundle: ThemeBundle;
    export default bundle;
}
