import { page } from "vitest/browser";
import * as sel from "@tryghost/test-data/selectors/settings";

const toast = () => page.getByRole("region", { name: /Notifications/ }).getByRole("listitem");

/** Settings locators and gestures shared by the acceptance batches; no assertions. */
export const settingsScreen = {
    section: (testId: string) => page.getByTestId(testId),
    titleAndDescription: () => page.getByTestId(sel.titleAndDescription),
    design: () => page.getByTestId(sel.design),
    users: () => page.getByTestId(sel.users),
    portal: () => page.getByTestId(sel.portal),
    explore: () => page.getByTestId(sel.explore),
    network: () => page.getByTestId(sel.network),
    tipsAndDonations: () => page.getByTestId(sel.tipsAndDonations),
    publicationLanguage: () => page.getByTestId(sel.publicationLanguage),
    timezone: () => page.getByTestId(sel.timezone),
    socialAccounts: () => page.getByTestId(sel.socialAccounts),
    seoMeta: () => page.getByTestId(sel.seoMeta),
    localeSelect: () => page.getByTestId(sel.localeSelect),
    timezoneSelect: () => page.getByTestId(sel.timezoneSelect),
    seoTabView: () => page.getByTestId(sel.seoTabView),
    selectOption: (name: string) => page.getByRole("option").filter({ hasText: name }),
    selectOptionExact: (name: string) => page.getByRole("option", { name: new RegExp(`^${name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}(?:\\s|$)`) }),
    errorToast: toast,
    successToast: toast,
    inviteUserModal: () => page.getByTestId(sel.inviteUserModal),
    limitModal: () => page.getByTestId(sel.limitModal),
    enableNewsletters: () => page.getByTestId(sel.enableNewsletters),
    defaultRecipients: () => page.getByTestId(sel.defaultRecipients),
    defaultRecipientsSelect: () => page.getByTestId(sel.defaultRecipientsSelect),
    emails: () => page.getByTestId(sel.emails),
    memberEmails: () => page.getByTestId(sel.memberEmails),
    newsletters: () => page.getByTestId(sel.newsletters),
    mailgun: () => page.getByTestId(sel.mailgun),
    addNewsletterModal: () => page.getByTestId(sel.addNewsletterModal),
    newsletterModal: () => page.getByTestId(sel.newsletterModal),
    infoToast: toast,
    notification: (text: string) => page.getByRole("region", { name: /Notifications/ }).getByText(text, { exact: true }),
    access: () => page.getByTestId(sel.access),
    customFields: () => page.getByTestId(sel.customFields),
    customFieldModal: () => page.getByTestId(sel.customFieldModal),
    stripeModal: () => page.getByTestId(sel.stripeModal),
    tiers: () => page.getByTestId(sel.tiers),
    tierDetailModal: () => page.getByTestId(sel.tierDetailModal),
    analytics: () => page.getByTestId(sel.analytics),
    navigation: () => page.getByTestId(sel.navigation),
    navigationModal: () => page.getByTestId(sel.navigationModal),
    announcementBar: () => page.getByTestId(sel.announcementBar),
    announcementBarModal: () => page.getByTestId(sel.announcementBarModal),
    designModal: () => page.getByTestId(sel.designModal),
    welcomeEmailModal: () => page.getByTestId(sel.welcomeEmailModal),
    welcomeEmailCustomizeModal: () => page.getByTestId(sel.welcomeEmailCustomizeModal),
    welcomeEmailDirtyConfirmModal: () => page.getByTestId(sel.welcomeEmailDirtyConfirmModal),
    welcomeEmailModeEdit: () => page.getByTestId(sel.welcomeEmailModeEdit),
    welcomeEmailModePreview: () => page.getByTestId(sel.welcomeEmailModePreview),
    welcomeEmailPreviewSubject: () => page.getByTestId(sel.welcomeEmailPreviewSubject),
    welcomeEmailPreviewIframe: () => page.getByTestId(sel.welcomeEmailPreviewIframe),
    freeWelcomeEmailPreview: () => settingsScreen.memberEmails().getByTestId(sel.freeWelcomeEmailPreview),
    paidWelcomeEmailRow: () => settingsScreen.memberEmails().getByTestId(sel.paidWelcomeEmailRow),
    theme: () => page.getByTestId(sel.theme),
    themeModal: () => page.getByTestId(sel.themeModal),
    themeCodeEditorModal: () => page.getByTestId(sel.themeCodeEditorModal),
    themeEditorConfirmModal: () => page.getByTestId(sel.themeEditorConfirmModal),
    themeEditorInputModal: () => page.getByTestId(sel.themeEditorInputModal),
    menu: () => page.getByRole("menu"),
    menuItem: (name: string) => page.getByRole("menuitem", {name}),
    sidebar: () => page.getByTestId(sel.settingsSidebar),
    search: () => page.getByRole("textbox", {name: sel.settingsSearchLabel, exact: true}),
    exitButton: () => page.getByTestId(sel.exitSettings),
    confirmationModal: () => page.getByTestId(sel.confirmationModal),
    confirmationAction: (name: "Leave" | "Stay") => settingsScreen.confirmationModal().getByRole("button", { name }),
    portalModal: () => page.getByTestId(sel.portalModal),
    userDetailModal: () => page.getByTestId(sel.userDetailModal),
    exploreToggle: () => page.getByTestId(sel.exploreToggle),
    exploreGrowthToggle: () => page.getByTestId(sel.exploreGrowthToggle),
    explorePreview: () => page.getByTestId(sel.explorePreview),
    testimonialsModal: () => page.getByTestId(sel.exploreTestimonialsModal),
    migratedFromSelect: () => page.getByTestId(sel.migratedFrom),
    testimonialContent: () => page.getByPlaceholder(sel.testimonialPlaceholder),
    donateUrl: () => settingsScreen.tipsAndDonations().getByTestId(sel.donateUrl),
    previewShareableLink: () => settingsScreen.tipsAndDonations().getByTestId(sel.previewShareableLink),
    copyShareableLink: () => settingsScreen.tipsAndDonations().getByTestId(sel.copyShareableLink),
    suggestedAmount: () => settingsScreen.tipsAndDonations().getByRole("textbox", { name: sel.suggestedAmountLabel }),
    navItem: (name: string) => settingsScreen.sidebar().getByText(name, { exact: true }),
    noSearchResults: () => settingsScreen.sidebar().getByText(sel.noSearchResultsText, { exact: true }),

    async editTitle(value: string): Promise<void> {
        const section = settingsScreen.titleAndDescription();
        await section.getByRole("button", { name: "Edit" }).click();
        await section.getByLabelText(sel.siteTitleLabel).fill(value);
    },
};
