version: o.o
os: linux
files:
  - source: ./Ghost
    destination: /tmp
hooks:
 ApplicationStop:
  - location: scripts/application_stop.sh
    timeout: 300
    runas: ec2-user
Beforeinstall:
 - location: scripts/before_install.sh
   timeout: 300
   runas: ec2-user
AplicationStart:
 - location: scripts/application_start.sh
   timeout: 300
   runas: ec2-user
