# Ghost development environment - Ghost container and gateway
# Requires: compose.infra.yaml for MySQL, Redis, Mailpit
#
# Usage:
#   docker compose -f compose.infra.yaml -f compose.dev.yaml up
#   docker compose -f compose.infra.yaml -f compose.dev.yaml -f compose.analytics.yaml up  # With analytics

services:
  # Main development Ghost instance
  # Additional instances can be created programmatically via E2E GhostManager
  ghost-dev:
    build:
      context: ./
      dockerfile: docker/ghost-dev/Dockerfile
    container_name: ghost-dev
    working_dir: /home/ghost/ghost/core
    command: ["yarn", "dev"]
    volumes:
      - ./ghost:/home/ghost/ghost
      # Mount specific content subdirectories to preserve themes/adapters from source
      - ghost-dev-data:/home/ghost/ghost/core/content/data
      - ghost-dev-images:/home/ghost/ghost/core/content/images
      - ghost-dev-media:/home/ghost/ghost/core/content/media
      - ghost-dev-files:/home/ghost/ghost/core/content/files
      - ghost-dev-logs:/home/ghost/ghost/core/content/logs
      - shared-config:/mnt/shared-config:ro
    environment:
      NODE_ENV: development
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
      DEBUG: ${DEBUG:-}
      database__client: mysql2
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: ${MYSQL_ROOT_PASSWORD:-root}
      database__connection__database: ${MYSQL_DATABASE:-ghost_dev}
      server__host: 0.0.0.0
      server__port: 2368
      mail__transport: SMTP
      mail__options__host: mailpit
      mail__options__port: 1025
      # Redis cache (optional)
      adapters__cache__Redis__host: redis
      adapters__cache__Redis__port: 6379
      # Public app assets - proxied through Caddy gateway to host dev servers
      # Using /ghost/assets/* paths
      portal__url: /ghost/assets/portal/portal.min.js
      comments__url: /ghost/assets/comments-ui/comments-ui.min.js
      sodoSearch__url: /ghost/assets/sodo-search/sodo-search.min.js
      sodoSearch__styles: /ghost/assets/sodo-search/main.css
      signupForm__url: /ghost/assets/signup-form/signup-form.min.js
      announcementBar__url: /ghost/assets/announcement-bar/announcement-bar.min.js
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailpit:
        condition: service_healthy
      stripe:
        condition: service_healthy
        required: false
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:2368',{redirect:'manual'}).then(r=>process.exit(r.status<500?0:1)).catch(()=>process.exit(1))"]
      timeout: 5s
      retries: 10
      start_period: 5s

  # Caddy reverse proxy for the main dev instance
  # Routes Ghost backend + proxies asset requests to host dev servers
  ghost-dev-gateway:
    build:
      context: ./docker/dev-gateway
      dockerfile: Dockerfile
    container_name: ghost-dev-gateway
    ports:
      - "2368:80"
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount Caddyfile for live config changes without rebuilding
      - ./docker/dev-gateway/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      ghost-dev:
        condition: service_healthy

  stripe:
    image: stripe/stripe-cli:latest
    container_name: ghost-dev-stripe
    entrypoint: ["/entrypoint.sh"]
    profiles: ["stripe"]
    volumes:
      - ./docker/stripe/entrypoint.sh:/entrypoint.sh:ro
      - shared-config:/mnt/shared-config
    environment:
      - GHOST_URL=${GHOST_URL:-http://ghost-dev:2368}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
    healthcheck:
      test: ["CMD", "test", "-f", "/mnt/shared-config/.env.stripe"]
      interval: 1s
      retries: 120

volumes:
  shared-config:
  ghost-dev-data:
  ghost-dev-images:
  ghost-dev-media:
  ghost-dev-files:
  ghost-dev-logs:
