/**
 * Builds the full Ghost model graph on a bookshelf instance. Order matters:
 * a few models extend others at registration time (Author extends User,
 * TagPublic extends Tag), so dependencies come first.
 */

const factories = [
    require('./action'),
    require('./role'),
    require('./api-key'),
    require('./user'),
    require('./author'),
    require('./automated-email-recipient'),
    require('./automation'),
    require('./benefit'),
    require('./collection-post'),
    require('./collection'),
    require('./comment-like'),
    require('./comment-report'),
    require('./comment'),
    require('./custom-theme-setting'),
    require('./donation-payment-event'),
    require('./email-batch'),
    require('./email-design-setting'),
    require('./email-recipient-failure'),
    require('./email-recipient'),
    require('./email-spam-complaint-event'),
    require('./email'),
    require('./gift'),
    require('./integration'),
    require('./invite'),
    require('./job'),
    require('./label'),
    require('./member-cancel-event'),
    require('./member-click-event'),
    require('./member-created-event'),
    require('./member-email-change-event'),
    require('./member-feedback'),
    require('./member-login-event'),
    require('./member-newsletter'),
    require('./member-paid-subscription-event'),
    require('./member-payment-event'),
    require('./member-product-event'),
    require('./member-status-event'),
    require('./member-stripe-customer'),
    require('./member-subscribe-event'),
    require('./member'),
    require('./mention'),
    require('./milestone'),
    require('./mobiledoc-revision'),
    require('./newsletter'),
    require('./offer-redemption'),
    require('./offer'),
    require('./permission'),
    require('./post-revision'),
    require('./post'),
    require('./posts-meta'),
    require('./product'),
    require('./recommendation-click-event'),
    require('./recommendation-subscribe-event'),
    require('./recommendation'),
    require('./redirect'),
    require('./session'),
    require('./settings'),
    require('./single-use-token'),
    require('./snippet'),
    require('./stripe-customer-subscription'),
    require('./stripe-price'),
    require('./stripe-product'),
    require('./subscription-created-event'),
    require('./suppression'),
    require('./tag'),
    require('./tag-public'),
    require('./webhook'),
    require('./welcome-email-automated-email'),
    require('./welcome-email-automation-run'),
];

module.exports = function createModels(ghostBookshelf) {
    const models = {Base: ghostBookshelf};
    for (const factory of factories) {
        Object.assign(models, factory(ghostBookshelf));
    }
    return models;
};
