blank_issues_enabled: true
contact_links:
  - name: 🚑 Help & Support
    url: https://forum.ghost.org
    about: Please use the community forum for questions
  - name: 💡 Features & Ideas
    url: https://forum.ghost.org/c/Ideas
    about: Please vote for & post new ideas in the the forum
  - name: 📖 Documentation
    url: https://docs.ghost.org/
    about: Tutorials & reference guides for themes, the API and more
