name: ghost-testing
services:
  ghost:
    image: ghost:local
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../.yarncache:/home/ghost/.yarncache
    container_name: ghost-testing-ghost
    develop: 
      watch: 
        - path: ../
          action: sync
          target: /home/ghost
          ignore: 
            - node_modules/
            - .yarncache/
        - path: yarn.lock
          action: rebuild
    restart: always
    ports:
      - 2368:2368
      - 4200:4200
    environment:
      - NODE_ENV=testing
      - DEBUG=${DEBUG:-}
      - APP_FLAGS=${APP_FLAGS:-}
    tty: true

networks:
  default:
    name: ghost-testing-network