export const exploreSites = {
    uncategorized: {
        categoryName: 'Uncategorized',
        sites: [
            '@index@activitypub.ghost.org',
            '@index@www.404media.co',
            '@index@john.onolan.org',
            '@index@www.coffeeandcomplexity.com',
            '@index@ghost.codenamejimmy.com',
            '@index@www.cosmico.org',
            '@index@www.syphoncontinuity.com',
            '@index@www.russbrown.design',
            '@index@simone.org',
            '@index@www.lifeisasacredtext.com',
            '@index@torment-nexus.mathewingram.com',
            '@index@newsletter.mathewingram.com',
            '@index@birchtree.me',
            '@index@onemanandhisblog.com',
            '@index@blog.front-matter.io',
            '@index@securinglaravel.com',
            '@index@internet.exchangepoint.tech',
            '@index@postabdn.com',
            '@index@heureux-et-perches.ghost.io',
            '@index@deadsuperhero.com',
            '@index@broadbandbreakfast.com',
            '@index@www.peterzimon.com',
            '@index@www.thegist.ie',
            '@index@thoughtcicles.xyz',
            '@index@post.intrapology.com',
            '@index@a.wholelottanothing.org',
            '@index@www.testingcatalog.com',
            '@index@www.kryobot.io',
            '@index@www.marcellomancuso.ca',
            '@index@www.nevillehobson.io',
            '@index@www.leadsticks.com',
            '@index@minus1.ghost.io',
            '@index@blogpocket-week.ghost.io',
            '@index@erreur2000.info',
            '@index@www.nightwater.email',
            '@index@sagzy.io',
            '@index@bl.ag',
            '@index@michaelbrooks.co.uk',
            '@index@www.sounderatheart.com',
            '@index@transfer-orbit.ghost.io',
            '@index@www.jeremyajorgensen.com',
            '@index@www.djordje.blog',
            '@index@danielm.ghost.io',
            '@index@www.connectingcells.com',
            '@index@www.tourniquet.quebec',
            '@index@forbetter.ghost.io',
            '@index@idea.ghost.io',
            '@index@silverhuang.com',
            '@index@numericcitizen.me',
            '@index@spyglass.org',
            '@index@www.autumnwelles.com',
            '@index@improvesomething.today',
            '@index@www.sage.blue',
            '@index@www.onework.co',
            '@index@www.kinoki.co',
            '@index@www.gorillasun.de',
            '@index@www.trema.website',
            '@index@www.cabinetofdelights.com',
            '@index@www.savingsasaservice.com.au',
            '@index@leif.me',
            '@index@neunetz.com',
            '@index@peter.ghost.io',
            '@index@www.chrisraible.com',
            '@index@netapinotes.com',
            '@index@terrill-welch.ghost.io',
            '@index@mickaelremond.com',
            '@index@jonpainter.com',
            '@index@sannedv.com',
            '@index@princivershwal.ghost.io',
            '@index@longformers.ghost.io',
            '@index@www.poorlydrawnarsenal.com',
            '@index@tinjar.ghost.io',
            '@index@www.elliotcsmith.com',
            '@index@2tonwaffle.com',
            '@index@demo.spectralwebservices.com',
            '@index@www.clareifi.com',
            '@index@mitchellens.ink',
            '@index@vis-communication.ghost.io',
            '@index@www.dingran.me',
            '@index@www.siennaeggler.com',
            '@index@www.leicester.news',
            '@index@www.between-two-firewalls.com',
            '@index@guji.jjme.me',
            '@index@fabien.ghost.io',
            '@index@www.augment.ink',
            '@index@danielverastiqui.com',
            '@index@prod-test.ghost.io',
            '@index@zimo.ghost.io',
            '@index@www.allthingsservices.de',
            '@index@www.socialmediawatchblog.de',
            '@index@seabits.com',
            '@index@romanempiretimes.com',
            '@index@www.avant.dev',
            '@index@www.townhallcitizen.com',
            '@index@www.crucialtracks.org',
            '@index@blog.warrenweb.net',
            '@index@bibelotages.com',
            '@index@www.ryanhamilton.work',
            '@index@www.dalekeiger.net',
            '@index@onemilliongoal.com'
        ]
    }
    // featured: {
    //     categoryName: 'Featured',
    //     sites: [
    //         '@index@activitypub.ghost.org',
    //         '@index@john.onolan.org',
    //         '@caseynewton@mastodon.social'
    //     ]
    // },
    // news: {
    //     categoryName: 'News & journalism',
    //     sites: [
    //         '@404mediaco@mastodon.social',
    //         '@index@www.coffeeandcomplexity.com',
    //         '@index@www.syphoncontinuity.com',
    //         '@Flipboard@flipboard.social'
    //     ]
    // },
    // technology: {
    //     categoryName: 'Technology',
    //     sites: [
    //         '@TechCrunch@mstdn.social',
    //         '@swf@socialwebfoundation.org',
    //         '@index@www.russbrown.design',
    //         '@index@ghost.codenamejimmy.com',
    //         '@arstechnica@mastodon.social'
    //     ]
    // },
    // business: {
    //     categoryName: 'Business',
    //     sites: [
    //         '@Forbes@newsie.social',
    //         '@index@www.cosmico.org'
    //     ]
    // }
};