/* eslint-disable */
// @generated by scripts/generate-locale-registry.js — DO NOT EDIT BY HAND.
// Public entry for the 'search' namespace. Import as '@tryghost/i18n/registry/search'.

import REGISTRY from './search.generated.mjs';
import {createNamespacedI18n} from '../esm-factory.mjs';

const i18n = createNamespacedI18n(REGISTRY, 'search');

export default i18n;
export const {LOCALE_DATA, SUPPORTED_LOCALES, generateResources} = i18n;
