# Base container and services for running Ghost
## Intended to be extended by another compose file
## e.g. docker compose -f base.compose.yml -f development.compose.yml up
## Does not include development dependencies, Ghost code, or any other dependencies
name: ghost-devcontainer
services:
  ghost:
    image: ghost-devcontainer
    command: ["sleep", "infinity"]
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      target: base-devcontainer
      args:
        WORKDIR: /workspaces/ghost
    pull_policy: never
    environment:
      - DEVCONTAINER=true
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  mysql:
    extends:
      file: ../compose.yml
      service: mysql
    container_name: ghost-devcontainer-mysql
  redis:
    extends:
      file: ../compose.yml
      service: redis
    container_name: ghost-devcontainer-redis

volumes:
  mysql-data:
  redis-data:
