{
 "title": "Ghost Dashboard",
 "description": "An overview of the Ghost process metrics.",
 "tags": [
  "node.js",
  "nodejs"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ghost_nodejs_eventloop_lag_seconds, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ghost_nodejs_eventloop_lag_seconds, instance)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node.js Version",
   "type": "stat",
   "description": "The version of Node.js.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "ghost_nodejs_version_info{}", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Node.js Restarts",
   "type": "stat",
   "description": "The number of times Node.js restarted.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(ghost_process_start_time_seconds{job=~\"$job\"}[$__range]))",
     "legendFormat": "Node.js"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(ghost_process_cpu_user_seconds_total{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "User CPU - {{job}}"
    },
    {
     "expr": "rate(ghost_process_cpu_system_seconds_total{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "System CPU - {{job}}"
    },
    {
     "expr": "rate(ghost_process_cpu_seconds_total{job=~\"$job\"}[1m]) * 100",
     "legendFormat": "Total CPU - {{job}}"
    }
   ]
  },
  {
   "title": "CPU Time Spent",
   "type": "timeseries",
   "description": "CPU time spent.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ghost_process_cpu_seconds_total{job=~\"$job\"}[$interval])",
     "legendFormat": "Total - {{job}}"
    },
    {
     "expr": "rate(ghost_process_cpu_system_seconds_total{job=~\"$job\"}[$interval])",
     "legendFormat": "System - {{job}}"
    },
    {
     "expr": "rate(ghost_process_cpu_user_seconds_total{job=~\"$job\"}[$interval])",
     "legendFormat": "User - {{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "Process Memory - {{job}}"
    },
    {
     "expr": "ghost_nodejs_heap_size_total_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Total - {{job}}"
    },
    {
     "expr": "ghost_nodejs_heap_size_used_bytes{job=~\"$job\"}",
     "legendFormat": "Heap Used - {{job}}"
    },
    {
     "expr": "ghost_nodejs_external_memory_bytes{job=~\"$job\"}",
     "legendFormat": "External Memory - {{job}}"
    }
   ]
  },
  {
   "title": "Active Handlers and Requests",
   "type": "timeseries",
   "description": "Number of active handle and active requests.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ghost_nodejs_active_handles_total{job=~\"$job\"}",
     "legendFormat": "Active Handler - {{job}}"
    },
    {
     "expr": "ghost_nodejs_active_requests_total{job=~\"$job\"}",
     "legendFormat": "Active Request - {{job}}"
    }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "timeseries",
   "description": "Latency of the event loop.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ghost_nodejs_eventloop_lag_seconds{job=~\"$job\"}",
     "legendFormat": "Last - {{job}}"
    },
    {
     "expr": "ghost_nodejs_eventloop_lag_p99_seconds{job=~\"$job\"}",
     "legendFormat": "P99 - {{job}}"
    },
    {
     "expr": "ghost_nodejs_eventloop_lag_p50_seconds{job=~\"$job\"}",
     "legendFormat": "P50 - {{job}}"
    }
   ]
  },
  { "title": "Database: Connection Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "The number of active connections maintained with the database. These connections can be in use or idle.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "ghost_db_connection_pool_max{job=\"$job\"}",
     "legendFormat": "Max - {{job}}"
    },
    {
     "expr": "ghost_db_connection_pool_active{job=\"$job\"}",
     "legendFormat": "Active - {{job}}"
    },
    {
     "expr": "ghost_db_connection_pool_min{job=\"$job\"}",
     "legendFormat": "Min - {{job}}"
    }
   ]
  },
  {
   "title": "Pool Utilization",
   "type": "timeseries",
   "description": "The number of active connections as a percentage of the maximum allowed by the pool.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ghost_db_connection_pool_active{job=~\"$job\"} / ghost_db_connection_pool_max{job=~\"$job\"}",
     "legendFormat": "Active - {{job}}"
    }
   ]
  },
  {
   "title": "Time to Acquire Connection",
   "type": "timeseries",
   "description": "The elapsed time a transaction spends waiting for an available connection in the connection pool.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "ghost_db_connection_acquire_duration_seconds{quantile=\"0.5\", job=~\"$job\"}",
     "legendFormat": "P50 - {{job}}"
    },
    {
     "expr": "ghost_db_connection_acquire_duration_seconds{quantile=\"0.9\", job=~\"$job\"}",
     "legendFormat": "P90 - {{job}}"
    },
    {
     "expr": "ghost_db_connection_acquire_duration_seconds{quantile=\"0.99\", job=~\"$job\"}",
     "legendFormat": "P99 - {{job}}"
    }
   ]
  },
  {
   "title": "Pending Acquires",
   "type": "timeseries",
   "description": "The number of transactions that are currently in the queue waiting to acquire a free connection",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "ghost_db_connection_pool_pending_acquires{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Pending Creates",
   "type": "timeseries",
   "description": "The number of connections waiting to be established with the database.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "ghost_db_connection_pool_pending_creates{job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Database: Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "ghost_db_query_duration_seconds{quantile=\"0.5\", job=~\"$job\"}",
     "legendFormat": "P50 - {{job}}"
    },
    {
     "expr": "ghost_db_query_duration_seconds{quantile=\"0.9\", job=~\"$job\"}",
     "legendFormat": "P90 - {{job}}"
    },
    {
     "expr": "ghost_db_query_duration_seconds{quantile=\"0.99\", job=~\"$job\"}",
     "legendFormat": "P99 - {{job}}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "The number of queries executed in the trailing 60s.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "QPM" } },
   "targets": [
    {
     "expr": "rate(ghost_db_query_duration_seconds_count{job=~\"$job\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Garbage Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "GC Duration Rate",
   "type": "timeseries",
   "description": "Rate of garbage collection duration.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(ghost_nodejs_gc_duration_seconds_sum{job=~\"$job\"}[$interval])",
     "legendFormat": "{{kind}} - {{job}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Duration of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ghost_nodejs_gc_duration_seconds_sum{job=~\"$job\"}",
     "legendFormat": "{{kind}} - {{job}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "Usage of heap memory.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ghost_nodejs_heap_size_total_bytes{job=~\"$job\"}",
     "legendFormat": "Total - {{job}}"
    },
    {
     "expr": "ghost_nodejs_heap_size_used_bytes{job=~\"$job\"}",
     "legendFormat": "Used - {{job}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "Resident - {{job}}"
    },
    {
     "expr": "ghost_nodejs_external_memory_bytes{job=~\"$job\"}",
     "legendFormat": "External - {{job}}"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "description": "Rate of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(ghost_nodejs_gc_duration_seconds_count{job=~\"$job\"}[$interval])",
     "legendFormat": "{{kind}} - {{job}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "description": "Count of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ghost_nodejs_gc_duration_seconds_count{job=~\"$job\"}",
     "legendFormat": "{{kind}} - {{job}}"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "timeseries",
   "description": "Usage of heap space.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ghost_nodejs_heap_space_size_used_bytes{job=~\"$job\"}",
     "legendFormat": "{{space}} - {{job}}"
    }
   ]
  }
 ]
}