# For use in a Dev Container where your local code is mounted into the container
name: ghost-devcontainer
services:
  ghost:
    image: ghost-base-devcontainer
    build:
      target: base-devcontainer
    command: ["sleep", "infinity"]
    environment:
      - DEVCONTAINER=true
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix