name: ghost-devcontainer

services:
  ghost:
    image: ghost-devcontainer
    build:
      target: devbase
    command: ["sleep", "infinity"]
    environment:
      - DEVCONTAINER=true
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - 2368:2368
      - 4200:4200
      - 4173:4173
      - 41730:41730
      - 4175:4175
      - 4176:4176
      - 4177:4177
      - 4178:4178
      - 6174:6174
      - 7173:7173
      - 7174:7174
      - 9174:9174