name: ghost-development
services:
  ghost:
    build:
      target: full-devcontainer
    command: ["yarn", "dev"]
    volumes:
      - ../.yarncache:/home/ghost/.yarncache
    develop: 
      watch: 
        - path: ../
          action: sync
          target: /home/ghost
          ignore: 
            - node_modules/
            - .yarncache/
        - path: yarn.lock
          action: rebuild
    ports:
      - 2368:2368
      - 4200:4200
      - 4173:4173
      - 41730:41730
      - 4175:4175
      - 4176:4176
      - 4177:4177
      - 4178:4178
      - 6174:6174
      - 7173:7173
      - 7174:7174
      - 9174:9174
    environment:
      - DEBUG=${DEBUG:-}
      - APP_FLAGS=${APP_FLAGS:-}