/**
 * This file acts as an allowlist for "public" settings
 */

module.exports = {
    title: 'title',
    description: 'description',
    logo: 'logo',
    icon: 'icon',
    accent_color: 'accent_color',
    cover_image: 'cover_image',
    facebook: 'facebook',
    twitter: 'twitter',
    lang: 'locale',
    locale: 'locale',
    timezone: 'timezone',
    codeinjection_head: 'codeinjection_head',
    codeinjection_foot: 'codeinjection_foot',
    navigation: 'navigation',
    secondary_navigation: 'secondary_navigation',
    meta_title: 'meta_title',
    meta_description: 'meta_description',
    og_image: 'og_image',
    og_title: 'og_title',
    og_description: 'og_description',
    twitter_image: 'twitter_image',
    twitter_title: 'twitter_title',
    twitter_description: 'twitter_description',
    members_support_address: 'members_support_address',
    members_enabled: 'members_enabled',
    allow_self_signup: 'allow_self_signup',
    members_invite_only: 'members_invite_only',
    paid_members_enabled: 'paid_members_enabled',
    firstpromoter_account: 'firstpromoter_account',
    portal_button_style: 'portal_button_style',
    portal_button_signup_text: 'portal_button_signup_text',
    portal_button_icon: 'portal_button_icon',
    portal_signup_terms_html: 'portal_signup_terms_html',
    portal_signup_checkbox_required: 'portal_signup_checkbox_required',
    portal_plans: 'portal_plans',
    portal_name: 'portal_name',
    portal_button: 'portal_button',
    comments_enabled: 'comments_enabled',
    recommendations_enabled: 'recommendations_enabled',
    outbound_link_tagging: 'outbound_link_tagging'
};
