routes:

# Optional: rename the pagination URL segment site-wide (default: page)
# pagination: page

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
