name: "Restore dependency & build cache"
description: "Restore the dependency & build cache."

runs:
  using: "composite"
  steps:
    - name: Check dependency cache
      id: dep-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.CACHED_DEPENDENCY_PATHS }}
        key: ${{ env.DEPENDENCY_CACHE_KEY }}

    - name: Check build cache
      uses: actions/cache/restore@v4
      id: build-cache
      with:
        path: ${{ env.CACHED_BUILD_PATHS }}
        key: ${{ github.sha }}

    - name: Warn if caches are not restored
      shell: bash
      if: steps.dep-cache.outputs.cache-hit != 'true' || steps.build-cache.outputs.cache-hit != 'true'
      run: |
        echo "::warning::One or more caches not found. This is expected on the first run with new cache keys."
        if [ "${{ steps.dep-cache.outputs.cache-hit }}" != "true" ]; then
          echo "::warning::Dependency cache not found for key: ${{ env.DEPENDENCY_CACHE_KEY }}"
        fi
        if [ "${{ steps.build-cache.outputs.cache-hit }}" != "true" ]; then
          echo "::warning::Build cache not found for key: ${{ github.sha }}"
        fi
