import assert from 'assert/strict';
import crypto from 'node:crypto';
import { sign, verify } from 'jsonwebtoken';
import { getPublicKeyInfo } from '../../../../core/server/lib/public-jwk';

// Fixed keys in the two PEM formats Ghost stores in `ghost_private_key` /
// `members_private_key`: PKCS#1 (generated by current and legacy Ghost) and
// PKCS#8 (present on some existing installs).
//
// The `kid` and JWK values below were captured from node-jose 2.2.0 before the
// migration to jose 6. They are golden values on purpose: if a change makes
// Ghost derive a different `kid`, every JWT issued before that change stops
// resolving against /.well-known/jwks.json.
const KEYS = {
  'PKCS#1': {
    pem: `-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEA1+5swhoWXx2neXImfN+5dH54MwiMaqgDbx9nnObagrdpgRVh
x6qD+yJIrJi2KJ5pwF3z8qq9zvVuXnJOTR/OI9877nUhjtzDNgm6E/AnlWuAQVAT
srB/WV96Agy2PaFjekCo3p7n2JTSUV55w7ZthXJxHwRyHIPzBNOnQBcbGOMUUY/Q
NVo6G8YacetKq4wRRfIchJi0+noCysLLjvE3UiEk2kcXm9AsplAGmZpiYpmeHry6
Hofvp9CJUGz8r3htalZuk9hOkqd7eEodubuev97qGptUqR3Iba5yciswaDodayl/
ubJJa0wrpQAY7ImD8rM+uu9Z1lMIwkJraIevGQIDAQABAoIBAGigW0xVrZ9a1Aox
eFqrYMYEfaNksfz/+eH/GopZBWmvC00DmkRP5/FodERFHoZh86XFIG3ls2CzZU4Y
Hr6Z+Z1CDl0FnkQFzgTCA8qjY9qvow6CiXjcsmgQriKOHEOSjovvBqQP5RD5U0sf
9uoQ29J8WDmKQux0Nu2QzIpuZ6/Pe8CipZOd8TlF3PvyWkgiDczmP5dNqVjoYvvP
xek2mZPqK+b88ROL5WZOLhc+2gHN/5PH30rpcIYk9nvhYifKOvIV0JUfHB2P/pwa
hgadGK5Jwy2yWHigsfCB1DUlucWc7IES7tzttxTMqpuX0QQPH2+lw0yWB2bOhUB9
VvYX5U0CgYEA9O/y9m6M7Ux/EGkNeV1kA7fRPxb0WH9Yb0W2TEPlG2il6EEK723L
PLFKNjZCZu4QXqibcMknrkFu6gZsNiK4h8rkk7FgfYf1mHsr9Km51BwOP5bUWzpv
USFSlZwICvzLDjogBniVUPyu8E75J9CnXb5J87IMHCYJE5q5FJUwbkMCgYEA4a8Z
SBtwE1gPXvVWmLM1GvyEZBpcxqY3E+arkLkDXR6BX4da9+ToYhXWWflbT0il53xT
a/XYxELbgqnE8PHrzaDsBmkPm9x543i+RfJSn8O6VuMFs4V0XFBmTgwkr8Wv8GuD
Yi7M4pzoGQPkD9lp0vQDPXz7XJtOC2FqNY80TXMCgYBxAPM7Nq3WHWDSFWWeBLRL
8tabIOACpF4MmEEO1pQxHQrOKJP++sy1Z6YxdL8V9eefhHKSinvALXgaiHQMVeCE
5dqnOUKnJ77rZohVDKkrbvYz6EZ5AHCzIYiUdbRQPWkBW1fDJIbfInUjcYwKDn3p
Bg3gXNixc+rkHJIfKOV7OQKBgDO63QKoN2JXtv4/IiBSQ4PyCa6gVE+8XbeUEhNU
NS8tBN6Oug1ETPfepYluHL3pmw2ac8y1R4CFCqfCnj/UVAaIMlGt10QUn2PCk2qZ
BtNUG+w6kV364xcd3rVZFzerCo8DNdRVgeUXriO9vpLbdORDxlJbyYoKlzMImz23
m3d9AoGAZsgalB5Dj8xe0AD8ItTue31+gAkTS1W7ne8H7TwvdhUx0PwUyEaxbHQb
UJzJfpnayIYLdWvpWucnWGPhSmVTve3ORwzmE3sy6RhPTH852Dl2MRfHOcVusB1x
8FqxYTp9gLmhUZ59vMKF034YzHXjUmuvgN1JO3dpfarVa7uLeFA=
-----END RSA PRIVATE KEY-----`,
    kid: 'elY66Oi6IcJjfCOzI0UGputcqVga1_xSaOY8zy99DaA',
    jwk: {
      kty: 'RSA',
      n: '1-5swhoWXx2neXImfN-5dH54MwiMaqgDbx9nnObagrdpgRVhx6qD-yJIrJi2KJ5pwF3z8qq9zvVuXnJOTR_OI9877nUhjtzDNgm6E_AnlWuAQVATsrB_WV96Agy2PaFjekCo3p7n2JTSUV55w7ZthXJxHwRyHIPzBNOnQBcbGOMUUY_QNVo6G8YacetKq4wRRfIchJi0-noCysLLjvE3UiEk2kcXm9AsplAGmZpiYpmeHry6Hofvp9CJUGz8r3htalZuk9hOkqd7eEodubuev97qGptUqR3Iba5yciswaDodayl_ubJJa0wrpQAY7ImD8rM-uu9Z1lMIwkJraIevGQ',
      e: 'AQAB',
    },
    identityToken:
      'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImVsWTY2T2k2SWNKamZDT3pJMFVHcHV0Y3FWZ2ExX3hTYU9ZOHp5OTlEYUEifQ.eyJzdWIiOiJlZ2dAZ2hvc3Qub3JnIiwicm9sZSI6IkxlZ2VuZCIsImlhdCI6MTc4ODkxMjMxNiwiZXhwIjoxNzg4OTEyNjE2LCJpc3MiOiJpc3N1ZXIuY29tIn0.zDwPD7cGaR9D5dXU-Oo7_fJhaLUOc0npoNxwYdf2YEGJ_UlGktLWnyrwPKlZeX1EHwBGaWsKYP8ZlNlCmfN5gxLlluyTCENjdmwsoCeQHkNm9dSfPG0NymzEfzFI4z9-JR3AXuGMNfp9zvdYlbx7CMKpFIcM_v-lvd7-cDt7lmY2cNOmiNFC-_rgQSzP0ZViQjsLROel9yVsV13fMKJVs5QbhmsWoXQ9R8WRizPwEbIEodZmLdWfUAFXD-cJKLieC4W8ho18VpczEpFpo_U6IeM0gjwhsvGtwZwd5HMa-7rDO8hkAZAFh7NPkTCYIDZOEKwZlK1J3anrlDQbuqVJTQ',
    memberToken:
      'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6ImVsWTY2T2k2SWNKamZDT3pJMFVHcHV0Y3FWZ2ExX3hTYU9ZOHp5OTlEYUEifQ.eyJzdWIiOiJtZW1iZXJAZ2hvc3Qub3JnIiwia2lkIjoiZWxZNjZPaTZJY0pqZkNPekkwVUdwdXRjcVZnYTFfeFNhT1k4enk5OURhQSIsInNjb3BlIjoibWVtYmVyczppZGVudGl0eSIsImlhdCI6MTc4ODkxMjMxNiwiZXhwIjoxNzg4OTEyOTE2LCJhdWQiOiJodHRwczovL2V4YW1wbGUuY29tL21lbWJlcnMvYXBpIiwiaXNzIjoiaHR0cHM6Ly9leGFtcGxlLmNvbS9tZW1iZXJzL2FwaSJ9.rc4IYD7VGJHDKeBLgA93GZbLxhpUlCvkEZxxjsEPdqdy0cxhg3jj2_iFlOsAdppY7r9colsPXlOtqDrHz3c7pbOu4He5X6xHPH0rHlxTUqeAP5wnxZCtfMtaXtXYPWQPdGoMT_zvakSkrqCaxWQ2lkAz8WNGEl6fUgIrBXQd_4tHrd4eWZ3Ixd4kFsSO5f-9_MtZiiFvhlB0szPWcblTM0Ji2uQd0mmxCbD4u3lVttqLGmqyAjVYRddrnncZU6vtQRzOSVB_EktXvGFjHi8Fxq9Gfi3jPfkOOwt-sWOxYZ6Q-6ICWbk6JQ3m2eh6gPY8ys_yccbmZP4t-g3CJnLd1g',
  },
  'PKCS#8': {
    pem: `-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCYhlD7QVSExM/t
qtFuJh5tJVMInFMNdoYVTFC+1uEMJnaNfSgvI1fpBSbhBc9Dirg76RNh1uUbX/fm
tpanZ2TULkh4e7MqOI4gIyrsyxT5ouRGYFEdXMGGLBfffwTC8e6ndoKyRq6hF1PO
UOgcSAEh5UalRsftfLNpmDJNjIKKkfRoHovyVhwi5QBaD7VjTdDR1ip0CSA1Xn5l
MxHc3mLnshAqaLu4aDcyFE8z70IyhwUcRYkYniZG6HlbaTyOL/tDCmVCjt3rvMGh
TzAOhxdB5UKzV/9gC4rpKgaK2BSh+e5FT9UMEgXmRQXuxKMuCb5iF5l326LgYwtX
tsqrc6ePAgMBAAECggEAQA2kQ6gfePR4R9zFQAdVHsweb07LGCvOynH2tPZjo2kh
v3Cwp/8lQ5As0DJS5RAEJ/DNeXi4VYM7hhHm+d2TfAIF4Ec+qjv+/+MU+0WcBOxS
BnYbioOyKAkra2oZ006rxXshDwJdAvzbbpkOqRXaF+SEAxPTEVqds/o9IdEg31Uf
OS/ZjH2XbtsVOTMbXB21RrgthdjYbcqZzVRD8gClOgo7i6nskZGZRFbmb96qBpCX
hkpRLEQJbOhmCHqkGStInjS41PIfzjYu5JjfDaFJQqnOpwWcmhj8SNej1ocEpTcU
7xH+M/tyW1v88qFZiPm8St7bSL9HqWz4S/bNBwlyuQKBgQDJgcPPDLCI8woSexAG
I4sHxaGGl4mmGlH321HEHNcQft2JWBBpXGqi+F8VsG7wUsGHdRiM6bqseg3b7szr
iodeyl6WL/4nrQdZP/5RCARgNCIP9scKWGSlPkBh60xKD4+g0p1hL6kCrzB8SXYr
NnIlMWcw8uV/D4eYb9qGtY1O1wKBgQDBxYiSyT0eum2yTnIva+CORIRoRpsXK0/y
StC/ydYPI7Ozb+rB5ep+b/F7UuQJjY8o+TPKGmxh608Do62sHDAPtR948aNxV1M5
mIIoiPciJsc32D2Gv+UVUhpTSO1ncaJ8mumngfdC+CSosDWxTZiGq4JU+ww+5402
R34gEVDuCQKBgE2Vgd+pQhsogFtHOI80hiYy6JMaq2vhvGeS8PNyKzf1sLRdzMvU
QlaHDI0cRkqPgmX2JsKyhyY7RDTGx+10g9RyVGK9Db0W+LpbUj6+uHiV+ftth4sr
J20b/8vzvYbSYPmJvgCaShd3flKMMkxHBUHeuJ13F/eI8is1/cxaAJM3AoGBAJHq
NREL9zmXe5mE1xl8q8mWMPrxCELnO7mhuxZhYA9gfCbIRUij4PQ7SeXrIotLDR32
opgzU6Bc+NAtxk9PnqWFZ+DEXaaw8pvxizoJAci22Nflv1ckU9a9T9OdnCCEgq5A
XWjlRpQoljptDtGoNA5dQrTJo4wPA9h297QgNgg5AoGAOlKZuC4Fa4RWaltvgLrQ
6twylZTGVSm/njtK/FYdTen1wmNG6rDhkBkOMJnQKwgtjQHke9XxOpqLZTePLNs6
m+HAlDNOZe7ryiuK7dj04wY2qoO/kCsxO9bR1M8LGRWFIHd4e8ExGWn5Qxk0/9X+
8/teeCoaDHNy7R6167uxyX8=
-----END PRIVATE KEY-----`,
    kid: 'JE2weNkEqGijidGIJwC-xJxZBNGt2B74jwtwpCnAar0',
    jwk: {
      kty: 'RSA',
      n: 'mIZQ-0FUhMTP7arRbiYebSVTCJxTDXaGFUxQvtbhDCZ2jX0oLyNX6QUm4QXPQ4q4O-kTYdblG1_35raWp2dk1C5IeHuzKjiOICMq7MsU-aLkRmBRHVzBhiwX338EwvHup3aCskauoRdTzlDoHEgBIeVGpUbH7XyzaZgyTYyCipH0aB6L8lYcIuUAWg-1Y03Q0dYqdAkgNV5-ZTMR3N5i57IQKmi7uGg3MhRPM-9CMocFHEWJGJ4mRuh5W2k8ji_7QwplQo7d67zBoU8wDocXQeVCs1f_YAuK6SoGitgUofnuRU_VDBIF5kUF7sSjLgm-YheZd9ui4GMLV7bKq3Onjw',
      e: 'AQAB',
    },
    identityToken:
      'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkpFMndlTmtFcUdpamlkR0lKd0MteEp4WkJOR3QyQjc0and0d3BDbkFhcjAifQ.eyJzdWIiOiJlZ2dAZ2hvc3Qub3JnIiwicm9sZSI6IkxlZ2VuZCIsImlhdCI6MTc4ODkxMjMxNiwiZXhwIjoxNzg4OTEyNjE2LCJpc3MiOiJpc3N1ZXIuY29tIn0.gKzZdJGtuhbZfgj3O4RWKtWijTRyD7gYUJx4qtoPgvU4TZlzO_8T3Ox0iz5cdKC00RS7bMBko0uZZzMIFJSa6g3Mn34GaaUgkSFmLhvy7Y3lgjobzvzyOEFzMsdiyxUhSqclqWWxXjiFJ_cB0V9FeDnIIYvTHOBblwraCtef0MtNTWZGJ0LprLsy8pTOR2d7JFZGzT4GyyolNH7oao5J7u2CunH3MzrT890IyfUCAcZ_bXmHZpfWKpw7508q_uWZA8Nk5NAv_eSSybthHImubKgaiZSCWGH6UBs4UeDGjUih2gHwiIf8C0GQ77FzNX5hymUajrmqB5Hh6GadxFLL-Q',
    memberToken:
      'eyJhbGciOiJSUzUxMiIsInR5cCI6IkpXVCIsImtpZCI6IkpFMndlTmtFcUdpamlkR0lKd0MteEp4WkJOR3QyQjc0and0d3BDbkFhcjAifQ.eyJzdWIiOiJtZW1iZXJAZ2hvc3Qub3JnIiwia2lkIjoiSkUyd2VOa0VxR2lqaWRHSUp3Qy14SnhaQk5HdDJCNzRqd3R3cENuQWFyMCIsInNjb3BlIjoibWVtYmVyczppZGVudGl0eSIsImlhdCI6MTc4ODkxMjMxNiwiZXhwIjoxNzg4OTEyOTE2LCJhdWQiOiJodHRwczovL2V4YW1wbGUuY29tL21lbWJlcnMvYXBpIiwiaXNzIjoiaHR0cHM6Ly9leGFtcGxlLmNvbS9tZW1iZXJzL2FwaSJ9.FN60wS3MByDArPUMF3ebTGymncfhdw368lesUDx4uSR_iFBawqdN5KvbbAYeU0o33rACWJeaixb67o5OnhQ9Jamny67D06a1Cjl2cyecWvs2wCCFVKsBE9TRRXElmSpN8SVt46QKQcTCO9ahhzZ9sVy8wUNX8hc6Ucvv434nVHsgf_HSTbDfsJCPRal8dN5gYVJQ960t1qMjuvEJDedWRBuMtZENEsCwex0XBtUB47_cjML9Gxxd0kJs9Xar6WYt1hb3vzJpPeGLgnbvXNe268-NfK8uLPie1jwkyzDIYPxXQgAqUiB2zLGPZaWn1FFtTEjBk8d0BB8LXDVPndVbIA',
  },
};

const PRIVATE_JWK_FIELDS = ['d', 'p', 'q', 'dp', 'dq', 'qi', 'oth'];

describe('public-jwk', function () {
  for (const [format, fixture] of Object.entries(KEYS)) {
    describe(format, function () {
      it('derives the same kid node-jose derived', async function () {
        const { kid } = await getPublicKeyInfo(fixture.pem);

        assert.equal(kid, fixture.kid);
      });

      it('exports the same public JWK node-jose exported', async function () {
        const { jwk } = await getPublicKeyInfo(fixture.pem);

        assert.deepEqual(jwk, fixture.jwk);
      });

      it('exposes no private key parameters', async function () {
        const { jwk } = await getPublicKeyInfo(fixture.pem);

        assert.deepEqual(Object.keys(jwk).sort(), ['e', 'kty', 'n']);

        for (const field of PRIVATE_JWK_FIELDS) {
          assert.equal(field in jwk, false, `${field} must not be exported`);
        }

        assert.equal(JSON.stringify(jwk).includes('PRIVATE'), false);
      });

      // Tokens signed before the migration carry the node-jose kid in their
      // header, and must still verify against the key we now publish.
      it('verifies tokens issued before the migration', async function () {
        const { kid, jwk } = await getPublicKeyInfo(fixture.pem);
        const publicKey = crypto
          .createPublicKey({ key: jwk as crypto.JsonWebKey, format: 'jwk' })
          .export({ type: 'spki', format: 'pem' }) as string;

        for (const token of [fixture.identityToken, fixture.memberToken]) {
          const header = JSON.parse(Buffer.from(token.split('.')[0], 'base64url').toString('utf8'));

          assert.equal(header.kid, kid);
          // Fixed fixtures, so expiry is not what is under test here.
          assert.doesNotThrow(() => verify(token, publicKey, { ignoreExpiration: true }));
        }
      });

      it('verifies tokens issued after the migration', async function () {
        const { kid, jwk } = await getPublicKeyInfo(fixture.pem);
        const publicKey = crypto
          .createPublicKey({ key: jwk as crypto.JsonWebKey, format: 'jwk' })
          .export({ type: 'spki', format: 'pem' }) as string;

        for (const algorithm of ['RS256', 'RS512'] as const) {
          const token = sign({ sub: 'egg@ghost.org' }, fixture.pem, {
            algorithm,
            keyid: kid,
            issuer: 'issuer.com',
            expiresIn: '5m',
          });

          const claims = verify(token, publicKey, { algorithms: [algorithm] });

          assert.equal(typeof claims === 'string' ? claims : claims.sub, 'egg@ghost.org');
        }
      });

      it('caches the parsed result per key', async function () {
        const first = await getPublicKeyInfo(fixture.pem);
        const second = await getPublicKeyInfo(fixture.pem);

        assert.equal(first, second);
      });
    });
  }

  it('gives every key its own cache entry', async function () {
    const first = await getPublicKeyInfo(KEYS['PKCS#1'].pem);
    const second = await getPublicKeyInfo(KEYS['PKCS#8'].pem);

    assert.notEqual(first.kid, second.kid);
  });

  describe('invalid keys', function () {
    const invalid = {
      'empty string': '',
      'not a PEM': 'definitely-not-a-key',
      'truncated PEM': KEYS['PKCS#1'].pem.slice(0, 200),
      'a public key': crypto
        .createPublicKey(KEYS['PKCS#1'].pem)
        .export({ type: 'pkcs1', format: 'pem' })
        .toString(),
    };

    for (const [name, pem] of Object.entries(invalid)) {
      it(`rejects ${name}`, async function () {
        await assert.rejects(getPublicKeyInfo(pem));
      });
    }

    it('rejects a non-RSA key', async function () {
      const { privateKey } = crypto.generateKeyPairSync('ec', {
        namedCurve: 'P-256',
        privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
        publicKeyEncoding: { type: 'spki', format: 'pem' },
      });

      await assert.rejects(getPublicKeyInfo(privateKey), /RSA/);
    });

    it('does not cache a failure', async function () {
      await assert.rejects(getPublicKeyInfo('not-a-key'));
      await assert.rejects(getPublicKeyInfo('not-a-key'));
    });
  });
});
