/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  // Legacy hook class on buttons that never set position; use [position:sticky]
  blocklist: ['sticky'],
  corePlugins: {
    // Portal's global styles own the iframe reset
    preflight: false,
  },
  theme: {
    // Portal's iframes set html { font-size: 62.5% }, so 1rem = 10px
    screens: {
      sm: '481px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: 'var(--black)',
      white: 'var(--white)',
      grey: {
        0: 'var(--grey0)',
        1: 'var(--grey1)',
        2: 'var(--grey2)',
        3: 'var(--grey3)',
        4: 'var(--grey4)',
        5: 'var(--grey5)',
        6: 'var(--grey6)',
        7: 'var(--grey7)',
        8: 'var(--grey8)',
        9: 'var(--grey9)',
        10: 'var(--grey10)',
        11: 'var(--grey11)',
        12: 'var(--grey12)',
        13: 'var(--grey13)',
        14: 'var(--grey14)',
      },
      red: {
        DEFAULT: 'var(--red)',
        dark: 'var(--darkerRed)',
      },
      yellow: 'var(--yellow)',
      green: 'var(--green)',
      brand: 'var(--brandcolor)',
    },
    spacing: {
      px: '1px',
      0: '0px',
      0.5: '0.2rem',
      1: '0.4rem',
      1.5: '0.6rem',
      2: '0.8rem',
      2.5: '1rem',
      3: '1.2rem',
      3.5: '1.4rem',
      4: '1.6rem',
      5: '2rem',
      6: '2.4rem',
      7: '2.8rem',
      8: '3.2rem',
      9: '3.6rem',
      10: '4rem',
      11: '4.4rem',
      12: '4.8rem',
      14: '5.6rem',
      16: '6.4rem',
      20: '8rem',
      24: '9.6rem',
      28: '11.2rem',
      32: '12.8rem',
      36: '14.4rem',
      40: '16rem',
      44: '17.6rem',
      48: '19.2rem',
      52: '20.8rem',
      56: '22.4rem',
      60: '24rem',
      64: '25.6rem',
      72: '28.8rem',
      80: '32rem',
      96: '38.4rem',
    },
    fontSize: {
      xs: '1.2rem',
      sm: '1.3rem',
      md: '1.4rem',
      base: '1.5rem',
      lg: '1.6rem',
      xl: '1.8rem',
      '2xl': '2rem',
      '3xl': '2.4rem',
      '4xl': '3.2rem',
    },
    borderRadius: {
      none: '0',
      sm: '0.2rem',
      DEFAULT: '0.4rem',
      md: '0.6rem',
      lg: '0.8rem',
      xl: '1.2rem',
      full: '9999px',
    },
    // Tailwind's defaults for these are rem-based and would render at 62.5%
    lineHeight: {
      none: '1',
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
    },
    maxWidth: {
      none: 'none',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
    },
    extend: {
      backgroundImage: {
        'select-chevron':
          "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%23aeaeae' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m6 9 6 6 6-6'/%3E%3C/svg%3E\")",
      },
      keyframes: {
        fadein: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1.0' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        popup: {
          '0%': { transform: 'translateY(-30px)', opacity: '0' },
          '1%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1.0' },
        },
        'popup-full-size': {
          '0%': { transform: 'translateY(0px)', opacity: '0' },
          '1%': { transform: 'translateY(30px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1.0' },
        },
        'popup-mobile': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1.0' },
        },
        'powered-fade-in': {
          '0%': { transform: 'scale(0.98)', opacity: '0' },
          '75%': { opacity: '1.0' },
          '100%': { transform: 'scale(1)' },
        },
        'notification-slidein': {
          '0%': { transform: 'translateX(380px)' },
          '60%': { transform: 'translateX(-6px)' },
          '100%': { transform: 'translateX(0)' },
        },
        'notification-slideout': {
          '0%': { transform: 'translateX(0)' },
          '30%': { transform: 'translateX(-10px)' },
          '100%': { transform: 'translateX(380px)' },
        },
        'notification-slidein-mobile': {
          '0%': { transform: 'translateY(-150px)' },
          '50%': { transform: 'translateY(6px)' },
          '100%': { transform: 'translateY(0)' },
        },
        'notification-slideout-mobile': {
          '0%': { transform: 'translateY(0)' },
          '35%': { transform: 'translateY(6px)' },
          '100%': { transform: 'translateY(-150px)' },
        },
        'mobile-tray-from-bottom': {
          '0%': { opacity: '0', transform: 'translateY(300px)' },
          '20%': { opacity: '1.0' },
          '100%': { transform: 'translateY(0)' },
        },
        'gh-portal-gift-email-fade': {
          from: { opacity: '0', transform: 'translateY(4px)' },
          to: { opacity: '1', transform: 'none' },
        },
        'gh-portal-share-more-menu-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
};
