name: Docker Build

on:
  # Allow manual triggering
  workflow_dispatch:
  # Add PR trigger with label requirement
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'pull_request') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'run-docker-build'))

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # List of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner }}/ghost-test
          # Generate tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
          # Set labels
          labels: |
            org.opencontainers.image.title=Ghost Development
            org.opencontainers.image.description=Ghost development build
            org.opencontainers.image.vendor=TryGhost
            maintainer=TryGhost

      - name: Display Docker metadata
        run: |
          echo "Generated tags:"
          echo "${{ steps.meta.outputs.tags }}"
          echo ""
          echo "Generated labels:"
          echo "${{ steps.meta.outputs.labels }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ghost-test:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ghost-test:buildcache,mode=max
