name: 'Label Issues & PRs'

on:
  workflow_dispatch:
  issues:
    types: [opened, closed, labeled]
  pull_request_target:
    types: [opened, closed, labeled]
  schedule:
    - cron:  '0 * * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'TryGhost'
    steps:
      - uses: tryghost/actions/actions/label-actions@5b3f016a2426d87bd67cf4823f2cc0d87b94da63 # main
