name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    name: Lint
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        env:
          FORCE_COLOR: 0
        with:
          node-version: 24

      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [22, 24]
    env:
      FORCE_COLOR: 1
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        env:
          FORCE_COLOR: 0
        with:
          node-version: ${{ matrix.node }}

      - run: corepack enable
      - run: pnpm install --frozen-lockfile
      - run: pnpm test

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7

  required-checks-pass:
    name: Required checks pass
    if: always()
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - name: Verify all required jobs succeeded
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
