name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
jobs:
  test:
    uses: tryghost/actions/.github/workflows/test.yml@9b2a4a48cd458728c438c7fc090b3863b494cd16 # main
    with:
      node-versions: '[22, 24]'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
