name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - 'renovate/*'
jobs:
  test:
    uses: tryghost/actions/.github/workflows/test.yml@5b3f016a2426d87bd67cf4823f2cc0d87b94da63 # main
    with:
      node-versions: '[22, 24]'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
