/* global process */
/**
 * Emits hand-authored `.d.ts` files into build/. The package ships JS source (no tsc
 * build), so these declaration files describe the public surface for TS consumers.
 */
const fs = require('fs');
const path = require('path');

const BUILD_DIR = path.join(__dirname, '..', 'build');
if (!fs.existsSync(BUILD_DIR)) {
    fs.mkdirSync(BUILD_DIR, {recursive: true});
}

const i18nDts = `// @generated by scripts/generate-types.js — DO NOT EDIT BY HAND.
import type {i18n as I18nextInstance} from 'i18next';

export interface LocaleDataEntry {
    code: string;
    name: string;
    [key: string]: unknown;
}

export type Namespace = 'ghost' | 'portal' | 'signup-form' | 'comments' | 'search' | 'theme';

export interface I18nFactory {
    (locale?: string, ns?: Namespace | string, options?: Record<string, unknown>): I18nextInstance;
    LOCALE_DATA: LocaleDataEntry[];
    SUPPORTED_LOCALES: string[];
    generateResources(locales: string[], ns: string): Record<string, Record<string, Record<string, string>>>;
    default: I18nFactory;
}

declare const i18n: I18nFactory;

export default i18n;
export declare const LOCALE_DATA: LocaleDataEntry[];
export declare const SUPPORTED_LOCALES: string[];
export declare function generateResources(
    locales: string[],
    ns: string
): Record<string, Record<string, Record<string, string>>>;
`;

const registryDts = `// @generated by scripts/generate-types.js — DO NOT EDIT BY HAND.
// Types for the per-namespace subpath exports, e.g. '@tryghost/i18n/registry/portal'.
import type {I18nFactory, LocaleDataEntry} from './i18n';

declare const i18n: I18nFactory;

export default i18n;
export declare const LOCALE_DATA: LocaleDataEntry[];
export declare const SUPPORTED_LOCALES: string[];
export declare function generateResources(
    locales: string[],
    ns: string
): Record<string, Record<string, Record<string, string>>>;
`;

fs.writeFileSync(path.join(BUILD_DIR, 'i18n.d.ts'), i18nDts);
fs.writeFileSync(path.join(BUILD_DIR, 'registry.d.ts'), registryDts);

process.stdout.write('Wrote build/i18n.d.ts + build/registry.d.ts\n');
